###send a message

POST http://localhost:3002/api/chat/messages
Content-Type: application/json

{
    "senderId": "4",
    "receiverId": "7",
    "message": "Hello, this is a test message. Have you received it?"
}

###send a message

POST http://localhost:3002/api/chat/messages
Content-Type: application/json

{
    "senderId": "7",
    "receiverId": "4",
    "message": "Yes I have, this is another message."
}

###Get all messages between two users

GET http://localhost:3002/api/chat/messages/7/4


###get conversation history of a user
GET http://localhost:3002/api/chat/conversations/7


####get conversation history of a user with the auth middleware
GET http://localhost:3002/api/chat/conversations


###Get all messages between two users with auth middleware

GET http://localhost:3002/api/chat/messages/4



###Initializa a conversation from the server, without the auth middleware
POST http://localhost:3002/chat/initialize-conversation
Content-Type: application/json

{
    "senderId": "10",
    "receiverId": "4",
    "message": "Hello, this message was sent from the server to initialize the conversation."
}