version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend

  backend:
    build:
      context: ./login-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_SERVER=host.docker.internal
      - DB_PORT=1433
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=nuclearAppUsersDB