version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    depends_on:
      - login-service
      - chat-service
    networks:
      - app-network

  login-service:
    build:
      context: ./login-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_SERVER=host.docker.internal
      - DB_PORT=1433
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=nuclearAppUsersDB
    networks:
      - app-network
  
  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/NuclearAppMessages
    depends_on:
      - mongo
    volumes:
      - ./login-service/src/utils/authorize.js:/app/src/utils/authorize.js
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    

volumes:
  mongo_data:

networks:
  app-network: